SoftEng-HEIGVD/Teaching-HEIGVD-RES-2021-Chill

- src/main/java/ch/heigvd/res/chill/domain/LeonardBesseau/Guinness.java
- src/test/java/ch/heigvd/res/chill/domain/LeonardBesseau/GuinnessTest.java
> Add Guinness with tests

- src/main/java/ch/heigvd/res/chill/domain/roosemberth/Embuscade.java
- src/test/java/ch/heigvd/res/chill/domain/roosemberth/EmbuscadeTest.java
> Add 'Embuscade' beer

- src/main/java/ch/heigvd/res/chill/domain/roosemberth/Kwak.java
- src/test/java/ch/heigvd/res/chill/domain/roosemberth/KwakTest.java
> Add 'Kwak' beer

- src/main/java/ch/heigvd/res/chill/domain/Ga_3tan/Houleuse.java
- src/test/java/ch/heigvd/res/chill/domain/Ga_3tan/HouleuseTest.java
> Added Houleuse with tests

- src/main/java/ch/heigvd/res/chill/domain/dosseggegw1/Corona.java
- src/test/java/ch/heigvd/res/chill/domain/dosseggegw1/CoronaTest.java
> Add Corona with test

- src/main/java/ch/heigvd/res/chill/domain/KevinJordil/Wittekop.java
- src/test/java/ch/heigvd/res/chill/domain/KevinJordil/WittekopTest.java
> Add Wittekop beer with tests

- src/main/java/ch/heigvd/res/chill/domain/dosseggegw1/Boxer.java
- src/test/java/ch/heigvd/res/chill/domain/dosseggegw1/BoxerTest.java
> Add Boxer with test

- src/main/java/ch/heigvd/res/chill/domain/CassandreWoj/Stella.java
- src/test/java/ch/heigvd/res/chill/domain/CassandreWoj/StellaTest.java
> Add Stella beer and test

- src/main/java/ch/heigvd/res/chill/domain/CassandreWoj/Cardinal.java
- src/test/java/ch/heigvd/res/chill/domain/CassandreWoj/CardinalTest.java
> Cardinal beer added to the menu

- src/main/java/ch/heigvd/res/chill/domain/NicolasOgi/Brewdog.java
- src/test/java/ch/heigvd/res/chill/domain/NicolasOgi/BrewdogTest.java
> Add Brewdog with tests

- src/main/java/ch/heigvd/res/chill/domain/quillasp/Skunk.java
- src/test/java/ch/heigvd/res/chill/domain/quillasp/SkunkTest.java
As the title says, just test out some new things. You'll see, it'll be fun.
> Looking for some weed

- src/main/java/ch/heigvd/res/chill/domain/Nono98/LaFinDuMonde.java
- src/test/java/ch/heigvd/res/chill/domain/Nono98/LaFinDuMondeTest.java
> Add LaFinDuMonde with tests

- src/main/java/ch/heigvd/res/chill/domain/Nono98/Brouette.java
- src/test/java/ch/heigvd/res/chill/domain/Nono98/BrouetteTest.java
> Add Brouette with tests

- src/main/java/ch/heigvd/res/chill/domain/Nono98/Rivale.java
- src/test/java/ch/heigvd/res/chill/domain/Nono98/RivaleTest.java
> Add Rivale with tests

- src/main/java/ch/heigvd/res/chill/domain/nicrausaz/Tsingtao.java
- src/test/java/ch/heigvd/res/chill/domain/nicrausaz/TsingtaoTest.java
Just added Tsingtao
Closes #37
> Add Tsingtao + tests

- src/main/java/ch/heigvd/res/chill/domain/junodch/Water.java
- src/test/java/ch/heigvd/res/chill/domain/junodch/WaterTest.java
> Add Water with test

- src/main/java/ch/heigvd/res/chill/domain/rya_sge/Moon.java
- src/test/java/ch/heigvd/res/chill/domain/rya_sge/MoonTest.java
> Add Moon beer with test

- src/main/java/ch/heigvd/res/chill/domain/rya_sge/Pingu.java
- src/test/java/ch/heigvd/res/chill/domain/rya_sge/PinguTest.java
> Add Pingu beer with test 

- src/main/java/ch/heigvd/res/chill/domain/mhganh/Boxer.java
- src/main/java/ch/heigvd/res/chill/domain/mhganh/Duvel.java
- src/main/java/ch/heigvd/res/chill/domain/mhganh/LaCorne.java
- src/main/java/ch/heigvd/res/chill/domain/mhganh/LaFranche.java
- src/main/java/ch/heigvd/res/chill/domain/mhganh/PunkIPA.java
- src/test/java/ch/heigvd/res/chill/domain/mhganh/BoxerTest.java
- src/test/java/ch/heigvd/res/chill/domain/mhganh/DuvelTest.java
- src/test/java/ch/heigvd/res/chill/domain/mhganh/LaCorneTest.java
- src/test/java/ch/heigvd/res/chill/domain/mhganh/LaFrancheTest.java
- src/test/java/ch/heigvd/res/chill/domain/mhganh/PunkIPATest.java
> Change package name

- src/main/java/ch/heigvd/res/chill/domain/LoisDiserens/JoratBlanche.java
- src/test/java/ch/heigvd/res/chill/domain/LoisDiserens/JoratBlancheTest.java
Bonjour, voici ma première PR, pour l'ajout d'une bière au projet, fait selon la Playlist YT.
> Ajout de la Jorat Blanche

- src/main/java/ch/heigvd/res/chill/domain/AliceThunderWind/IceTea.java
- src/test/java/ch/heigvd/res/chill/domain/AliceThunderWind/IceTeaTest.java
> Add Ice Tea with tests

- src/main/java/ch/heigvd/res/chill/domain/TheSnekySnek/Blast.java
- src/test/java/ch/heigvd/res/chill/domain/TheSnekySnek/BlastTest.java
> Add Blast with tests

- src/main/java/ch/heigvd/res/chill/domain/TheSnekySnek/Lager.java
- src/test/java/ch/heigvd/res/chill/domain/TheSnekySnek/LagerTest.java
> Add Lager with tests

- src/main/java/ch/heigvd/res/chill/domain/noahfusi/LaChouffe.java
- src/test/java/ch/heigvd/res/chill/domain/noahfusi/LaChouffeTest.java
> Add Chouffe with tests

- src/main/java/ch/heigvd/res/chill/domain/LordTT/Delirium.java
- src/test/java/ch/heigvd/res/chill/domain/LordTT/DeliriumTest.java
closes #69 
Had to do 2 pushes because I forgot to stage all the files in the first one
> Fb delirum

- src/main/java/ch/heigvd/res/chill/domain/EmmanuelJanssens/Kwak.java
- src/test/java/ch/heigvd/res/chill/domain/EmmanuelJanssens/KwakTest.java
> Added Kwak to the menu with tests

- src/main/java/ch/heigvd/res/chill/domain/arbroween/Corona.java
- src/test/java/ch/heigvd/res/chill/domain/arbroween/CoronaTest.java
> Add Corona with tests

- src/main/java/ch/heigvd/res/chill/domain/EmmanuelJanssens/Pecheresse.java
- src/test/java/ch/heigvd/res/chill/domain/EmmanuelJanssens/PecheresseTest.java
> Added Pecheresse with test

- src/main/java/ch/heigvd/res/chill/domain/LordTT/Swaf.java
- src/test/java/ch/heigvd/res/chill/domain/LordTT/SwafTest.java
> Added Swaf with tests

- src/main/java/ch/heigvd/res/chill/domain/EmmanuelJanssens/Leffe.java
- src/test/java/ch/heigvd/res/chill/domain/EmmanuelJanssens/LeffeTest.java
> Added Leffe with tests

- src/main/java/ch/heigvd/res/chill/domain/EmmanuelJanssens/Chimay.java
- src/test/java/ch/heigvd/res/chill/domain/EmmanuelJanssens/ChimayTest.java
> Added chimay with test

- src/main/java/ch/heigvd/res/chill/domain/arbroween/TacticalNuclearPenguin.java
- src/test/java/ch/heigvd/res/chill/domain/arbroween/TacticalNuclearPenguinTest.java
> Add TacticalNuclearPenguin with tests

- src/main/java/ch/heigvd/res/chill/domain/Klab93/AlexLeRouge.java
- src/test/java/ch/heigvd/res/chill/domain/Klab93/AlexLeRougeTest.java
> add AlexLeRouge

- src/main/java/ch/heigvd/res/chill/domain/QuentinForestier/Namur.java
- src/test/java/ch/heigvd/res/chill/domain/QuentinForestier/NamurTest.java
> Add namur beer + tests

- src/main/java/ch/heigvd/res/chill/domain/MazieroMarco/GrapeFruit.java
- src/test/java/ch/heigvd/res/chill/domain/MazieroMarco/GrapeFruitTest.java
> Added GrapeFruit with tests

- src/main/java/ch/heigvd/res/chill/domain/fabio10000/LeffeBlonde.java
- src/test/java/ch/heigvd/res/chill/domain/fabio10000/LeffeBlondeTest.java
Please have a look at my proposal. It should close #104
> Add Leffe blonde to menu

- src/main/java/ch/heigvd/res/chill/domain/PaulReeve717/CuveeDesSeigneurs.java
- src/test/java/ch/heigvd/res/chill/domain/PaulReeve717/CuveeDesSeigneursTest.java
> add 'Cuvée des Seigneurs' with tests

- src/main/java/ch/heigvd/res/chill/domain/fabio10000/Guinness.java
- src/test/java/ch/heigvd/res/chill/domain/fabio10000/GuinnessTest.java
Please have a look at my proposal. It should close #103
> Add Guinness to menu

- src/main/java/ch/heigvd/res/chill/domain/soso24soso/JusDePomme.java
- src/test/java/ch/heigvd/res/chill/domain/soso24soso/JusDePommeTest.java
> Add JusDePomme with tests

- src/main/java/ch/heigvd/res/chill/domain/MazieroMarco/IceTea.java
- src/test/java/ch/heigvd/res/chill/domain/MazieroMarco/IceTeaTest.java
> Added IceTea drink and tests

- src/main/java/ch/heigvd/res/chill/domain/doublei/AmsterdamMaximator.java
- src/test/java/ch/heigvd/res/chill/domain/doublei/AmsterdamMaximatorTest.java
> Add Amsterdam Maximator with tests

- src/main/java/ch/heigvd/res/chill/domain/ubervison/PereJakob.java
- src/test/java/ch/heigvd/res/chill/domain/ubervison/PereJakobTest.java
> Add Père Jakob beer with associated tests

- src/main/java/ch/heigvd/res/chill/domain/ubervison/LaSorciere.java
- src/test/java/ch/heigvd/res/chill/domain/ubervison/LaSorciereTest.java
> Add La Sorcière beer with associated tests

- src/main/java/ch/heigvd/res/chill/domain/EricBroutba/Pepsi.java
- src/test/java/ch/heigvd/res/chill/domain/EricBroutba/PepsiTest.java
> Add Pepsi with tests

- src/main/java/ch/heigvd/res/chill/domain/danydacosta/Guinneuch.java
- src/test/java/ch/heigvd/res/chill/domain/danydacosta/GuinneuchTest.java
Please have a look at my proposal, it should close #133
> Add Guinneuch to the menu, with tests

- src/main/java/ch/heigvd/res/chill/domain/alecberney/LaSoeurBerney.java
- src/test/java/ch/heigvd/res/chill/domain/alecberney/LaSoeurBerneyTest.java
> Add La Soeur Berney with tests

- src/main/java/ch/heigvd/res/chill/domain/danydacosta/LeffeRuby.java
- src/test/java/ch/heigvd/res/chill/domain/danydacosta/LeffeRubyTest.java
> Add Leffe Ruby to the menu, with tests

- src/main/java/ch/heigvd/res/chill/domain/Insuline13/Eve.java
- src/test/java/ch/heigvd/res/chill/domain/Insuline13/EveTest.java
> Add Eve with tests

- src/main/java/ch/heigvd/res/chill/domain/FionaGbn/CocaZero.java
- src/test/java/ch/heigvd/res/chill/domain/FionaGbn/CocaZeroTest.java
> Add CocaZero with tests

- src/main/java/ch/heigvd/res/chill/domain/Meridas/Kirin.java
- src/test/java/ch/heigvd/res/chill/domain/Meridas/KirinTest.java
> Kirin beer addition

- src/main/java/ch/heigvd/res/chill/domain/K_do/Water.java
- src/test/java/ch/heigvd/res/chill/domain/K_do/WaterTest.java
> Add Water with tests

- src/main/java/ch/heigvd/res/chill/domain/davidpellissier/SatanRed.java
- src/test/java/ch/heigvd/res/chill/domain/davidpellissier/SatanRedTest.java
Satan is here, now :D . Closes #145
> Add Satan with tests

- src/main/java/ch/heigvd/res/chill/domain/Cantondy/Brooklyn.java
- src/test/java/ch/heigvd/res/chill/domain/Cantondy/BrooklynTest.java
> Add Brooklyn with tests

- src/main/java/ch/heigvd/res/chill/domain/K_do/ArrogantBastardAle.java
- src/test/java/ch/heigvd/res/chill/domain/K_do/ArrogantBastardAleTest.java
> Add Arrogant Bastard Ale

- src/main/java/ch/heigvd/res/chill/domain/Insuline13/Sommersby.java
- src/test/java/ch/heigvd/res/chill/domain/Insuline13/SommersbyTest.java
> Add Sommersby with tests

- src/main/java/ch/heigvd/res/chill/domain/DavidGL17/Kamboucha.java
- src/test/java/ch/heigvd/res/chill/domain/DavidGL17/KambouchaTest.java
Closes #159 
added a new beverage named Kamboucha
> Add Kamboucha with tests

- src/main/java/ch/heigvd/res/chill/domain/MelvynHerzig/BirraMoretti.java
- src/test/java/ch/heigvd/res/chill/domain/MelvynHerzig/BirraMorettiTest.java
> Add Birra Moretti

- src/main/java/ch/heigvd/res/chill/domain/DSDaniel/Grimbergen.java
- src/test/java/ch/heigvd/res/chill/domain/DSDaniel/GrimbergenTest.java
> Add Grimbergen with tests

- src/main/java/ch/heigvd/res/chill/domain/AnthoJack/Bilz.java
- src/test/java/ch/heigvd/res/chill/domain/AnthoJack/BilzTest.java
Added Bilz as requested. Should close #142
> Added Bilz drink

- src/main/java/ch/heigvd/res/chill/domain/issolahma/MooBeer.java
- src/test/java/ch/heigvd/res/chill/domain/issolahma/MooBeerTest.java
Adding the new beer, MooBeer, to the menu, with tests
Close #174
> New beer (MooBeer) and test

- src/main/java/ch/heigvd/res/chill/domain/mathias_maillard/Budweiser.java
- src/test/java/ch/heigvd/res/chill/domain/mathias_maillard/BudweiserTest.java
> Add Budweiser with tests

- src/main/java/ch/heigvd/res/chill/domain/melvinmerk/CuveeDesTrolls.java
- src/test/java/ch/heigvd/res/chill/domain/melvinmerk/CuveeDesTrollsTest.java
> Fb cuvee des trolls

- src/main/java/ch/heigvd/res/chill/domain/MichaelRuckstuhl/Guinness.java
- src/test/java/ch/heigvd/res/chill/domain/MichaelRuckstuhl/GuinnessTest.java
> Guinness with tests

- src/main/java/ch/heigvd/res/chill/domain/DavidGL17/RumMiel.java
- src/test/java/ch/heigvd/res/chill/domain/DavidGL17/RumMielTest.java
Added rum miel to the products available, closes #175. Rum miel is a special kind of rum, with less alcohol but more sugar,
> Added Rum miel to the project, and tests

- src/main/java/ch/heigvd/res/chill/domain/issolahma/LemonJuice.java
- src/test/java/ch/heigvd/res/chill/domain/issolahma/LemonJuiceTest.java
Just add lemon juice to the menu
close #186
> Add lemon juice and test

- src/main/java/ch/heigvd/res/chill/domain/alecberney/LaGrandeAMeylan.java
- src/test/java/ch/heigvd/res/chill/domain/alecberney/LaGrandeAMeylanTest.java
> add La Grande à Meylan as new beer with tests

- src/main/java/ch/heigvd/res/chill/domain/RobertsonRhyan/Kolsch.java
- src/test/java/ch/heigvd/res/chill/domain/RobertsonRhyan/KolschTest.java
> Add 4Pines Kolsch with tests

- src/main/java/ch/heigvd/res/chill/domain/alecberney/LaMereRochat.java
- src/test/java/ch/heigvd/res/chill/domain/alecberney/LaMereRochatTest.java
> add the new fresh beer La Mère Rcohat with tests

- src/main/java/ch/heigvd/res/chill/domain/RebeccaTevaearai/Poggerino.java
- src/test/java/ch/heigvd/res/chill/domain/RebeccaTevaearai/PoggerinoTest.java
> Add Poggerino

- src/main/java/ch/heigvd/res/chill/domain/Cantondy/Pietra.java
- src/test/java/ch/heigvd/res/chill/domain/Cantondy/PietraTest.java
> Add Pietra to the list

- src/main/java/ch/heigvd/res/chill/domain/MichaelRuckstuhl/MikeBeer.java
- src/test/java/ch/heigvd/res/chill/domain/MichaelRuckstuhl/MikeBeerTest.java
> add MikeBeer

- src/main/java/ch/heigvd/res/chill/domain/mathias_maillard/GreenTea.java
- src/test/java/ch/heigvd/res/chill/domain/mathias_maillard/GreenTeaTest.java
Closes #184 
Correction of PR #189 which included another drink
> Fb greentea update

- src/main/java/ch/heigvd/res/chill/domain/CarlP97/Delirium.java
- src/test/java/ch/heigvd/res/chill/domain/CarlP97/DeliriumTest.java
> Add Delirium with tests

- src/main/java/ch/heigvd/res/chill/domain/PaulReeve717/Villageoise.java
- src/test/java/ch/heigvd/res/chill/domain/PaulReeve717/VillageoiseTest.java
> Add Villageoise with tests

- src/main/java/ch/heigvd/res/chill/domain/zoubaidas/Celtia.java
- src/test/java/ch/heigvd/res/chill/domain/zoubaidas/CeltiaTest.java
> Add Celtia beer with tests

- src/main/java/ch/heigvd/res/chill/domain/CarlP97/Barbar.java
- src/test/java/ch/heigvd/res/chill/domain/CarlP97/BarbarTest.java
> Add Barbar with tests

- src/main/java/ch/heigvd/res/chill/domain/jadegrli/Cidre.java
- src/test/java/ch/heigvd/res/chill/domain/jadegrli/CidreTest.java
> Add Cidre with tests

- src/main/java/ch/heigvd/res/chill/domain/Alessandro_AP/Poretti6.java
- src/test/java/ch/heigvd/res/chill/domain/Alessandro_AP/Poretti6Test.java
> Poretti6 beer

- src/main/java/ch/heigvd/res/chill/domain/AxelVallon/Stella.java
- src/test/java/ch/heigvd/res/chill/domain/AxelVallon/StellaTest.java
Close #220 Stella beer had been put
> The Stella beer had been haded

- src/main/java/ch/heigvd/res/chill/domain/Alessandro_AP/Limoncello.java
- src/test/java/ch/heigvd/res/chill/domain/Alessandro_AP/LimoncelloTest.java
> Limoncello liqueur

- .github/workflows/validate-student-work.yml
- src/main/java/ch/heigvd/res/chill/domain/OvichHeigVD/RedBull.java
- src/test/java/ch/heigvd/res/chill/domain/OvichHeigVD/RedBullTest.java
Included RedBull drink into product list with tests. Closes #52
> Add RedBull with tests

- src/main/java/ch/heigvd/res/chill/domain/nicrausaz/Sagres.java
- src/test/java/ch/heigvd/res/chill/domain/nicrausaz/SagresTest.java
Corrected my mistake from previous PR.
this closes #245
> Add sagres

- src/main/java/ch/heigvd/res/chill/domain/OvichHeigVD/Monster.java
- src/test/java/ch/heigvd/res/chill/domain/OvichHeigVD/MonsterTest.java
> Add Monster with tests

- src/main/java/ch/heigvd/res/chill/domain/KevinJordil/Wittekop.java
- src/test/java/ch/heigvd/res/chill/domain/KevinJordil/WittekopTest.java
Let's add again the wittekop beer which was removed with my second pull request
Closes #251
> Add Wittekop beer (again) with tests

- src/main/java/ch/heigvd/res/chill/domain/junodch/Coffee.java
- src/test/java/ch/heigvd/res/chill/domain/junodch/CoffeeTest.java
Closes #92 Correction of the previous PR.
> Added Coffee and test

- src/main/java/ch/heigvd/res/chill/domain/jadegrli/ClubMate.java
- src/test/java/ch/heigvd/res/chill/domain/jadegrli/ClubMateTest.java
> Correction test name club mate

- src/main/java/ch/heigvd/res/chill/domain/jadegrli/ClubMate.java
- src/test/java/ch/heigvd/res/chill/domain/jadegrli/ClubMateTest.java
> Add ClubMate

- src/main/java/ch/heigvd/res/chill/domain/LoisDiserens/FinDuMonde.java
- src/test/java/ch/heigvd/res/chill/domain/LoisDiserens/FinDuMondeTest.java
Correction des branch : un fichier par branch
> Ajout Fin du Monde

- src/main/java/ch/heigvd/res/chill/domain/LoisDiserens/JoratBlanche.java
- src/test/java/ch/heigvd/res/chill/domain/LoisDiserens/JoratBlancheTest.java
Correction branch : un fichier par branch
> Ajout Jorat Blanche

- src/main/java/ch/heigvd/res/chill/domain/Ga_3tan/Swaf.java
- src/test/java/ch/heigvd/res/chill/domain/Ga_3tan/SwafTest.java
> added Swaf beer v2

- src/main/java/ch/heigvd/res/chill/domain/pozniako16/Guinness.java
- src/test/java/ch/heigvd/res/chill/domain/pozniako16/GuinnessTest.java
- src/test/java/ch/heigvd/res/chill/domain/wasadigi/DuvelTest.java
> Redid the guinness test to correct name

- src/main/java/ch/heigvd/res/chill/domain/pozniako16/FinDuMonde.java
- src/test/java/ch/heigvd/res/chill/domain/pozniako16/FinDuMondeTest.java
> redid fin du monde to correct mistakes

- src/main/java/ch/heigvd/res/chill/domain/g5b7w3/Chimay.java
- src/test/java/ch/heigvd/res/chill/domain/g5b7w3/ChimayTest.java
> Add chimay with test

- src/main/java/ch/heigvd/res/chill/domain/RebeccaTevaearai/Pomelo.java
- src/test/java/ch/heigvd/res/chill/domain/RebeccaTevaearai/PomeloTest.java
> Add Pomelo 2

- src/main/java/ch/heigvd/res/chill/domain/volqfelko/Delirium.java
- src/test/java/ch/heigvd/res/chill/domain/volqfelko/DeliriumTest.java
> add Delirium with test

- src/main/java/ch/heigvd/res/chill/domain/wilfried01/Kadji.java
- src/test/java/ch/heigvd/res/chill/domain/wilfried01/KadjiTest.java
The Kadji Beer is now available for command.
> Client can now command a Kadji Beer

- src/main/java/ch/heigvd/res/chill/domain/wilfried01/Castel.java
- src/test/java/ch/heigvd/res/chill/domain/wilfried01/CastelTest.java
Castel is now available for command. This close #74
> A client can now command a Castel beer

- src/main/java/ch/heigvd/res/chill/domain/wilfried01/Beer33Export.java
- src/test/java/ch/heigvd/res/chill/domain/wilfried01/Beer33ExportTest.java
The client can now ask for a 33 Export beer. This close #73
> The 33 export beer has been added to the list

- src/main/java/ch/heigvd/res/chill/domain/maxscharwath/Speights.java
- src/test/java/ch/heigvd/res/chill/domain/maxscharwath/SpeightsTest.java
> Add Speight's Beer [2]

- src/main/java/ch/heigvd/res/chill/domain/JanisChiffelle/LaVaudruzienne.java
- src/test/java/ch/heigvd/res/chill/domain/JanisChiffelle/LaVaudruzienneTest.java
> Add La Vaudruzienne with test

- src/main/java/ch/heigvd/res/chill/domain/JanisChiffelle/LaPlume.java
- src/test/java/ch/heigvd/res/chill/domain/JanisChiffelle/LaPlumeTest.java
Proposal for a new beer. it close #289
> Add la plume with tests

- src/main/java/ch/heigvd/res/chill/domain/sist1998/Lav.java
- src/test/java/ch/heigvd/res/chill/domain/sist1998/LavTest.java
> Add Lav beer + tests

- src/main/java/ch/heigvd/res/chill/domain/AllemanoEn/PrixGarantie.java
- src/test/java/ch/heigvd/res/chill/domain/AllemanoEn/PrixGarantieTest.java
I've added the beer "Prix Garantie" and the corresponding tests
> Adding beer : Prix Garantie + test

- src/main/java/ch/heigvd/res/chill/domain/gabthr/PepsiMax.java
- src/test/java/ch/heigvd/res/chill/domain/gabthr/PepsiMaxTest.java
> add new drink PepsiMax with test

- src/main/java/ch/heigvd/res/chill/domain/gabthr/Chopfab.java
- src/test/java/ch/heigvd/res/chill/domain/gabthr/ChopfabTest.java
> Add new beer Chopfab with test

- src/main/java/ch/heigvd/res/chill/domain/maxscharwath/Swaf.java
- src/test/java/ch/heigvd/res/chill/domain/maxscharwath/SwafTest.java
> Add Swaf with tests

- src/main/java/ch/heigvd/res/chill/domain/AllemanoEn/DocteurGabs.java
- src/test/java/ch/heigvd/res/chill/domain/AllemanoEn/DocteurGabsTest.java
fb-clean is the fb that contains Docteur Gab's Beer
> Add Docteur Gab's with test (V2)

- src/main/java/ch/heigvd/res/chill/domain/g5b7w3/Kwak.java
- src/test/java/ch/heigvd/res/chill/domain/g5b7w3/KwakTest.java
Closes #266 
Clean version of #267
> Add Kwak with tests

- src/main/java/ch/heigvd/res/chill/domain/g5b7w3/Lupus.java
- src/test/java/ch/heigvd/res/chill/domain/g5b7w3/LupusTest.java
Closes #268
Clean version of #270
> Add Lupus with test

- src/main/java/ch/heigvd/res/chill/domain/davidpellissier/GoudenCarolus.java
- src/test/java/ch/heigvd/res/chill/domain/davidpellissier/GoudenCarolusTest.java
Contains only the two files of the beer and nothing more.  Closes #163
> (v2) Add Gouden Carolus

- src/main/java/ch/heigvd/res/chill/domain/yanik23/Paulaner.java
- src/test/java/ch/heigvd/res/chill/domain/yanik23/PaulanerTest.java
> Add Paulaner with tests

- src/main/java/ch/heigvd/res/chill/domain/AnthoJack/Rivella.java
- src/test/java/ch/heigvd/res/chill/domain/AnthoJack/RivellaTest.java
Added beverage "Rivella". Close #236
> Added Rivella

- src/main/java/ch/heigvd/res/chill/domain/sist1998/Fanta.java
- src/test/java/ch/heigvd/res/chill/domain/sist1998/FantaTest.java
> Add Fanta + tests

- src/main/java/ch/heigvd/res/chill/domain/yanik23/Lowenbrau.java
- src/test/java/ch/heigvd/res/chill/domain/yanik23/LowenbrauTest.java
> Add Lowenbrau with tests

- src/main/java/ch/heigvd/res/chill/domain/jlheig/Malandrin.java
- src/test/java/ch/heigvd/res/chill/domain/jlheig/MalandrinTest.java
Please have a look at my proposal. It should close #288
> Add Malandrin to the menu with tests

- src/main/java/ch/heigvd/res/chill/domain/jlheig/Hobgoblin.java
- src/test/java/ch/heigvd/res/chill/domain/jlheig/HobgoblinTest.java
Please have a look at my proposal. I corrected the Too Many Files mistake I made. It should close #309
> Add Hobgoblin to the menu
